[project]
name = "am-tratamento-dados-escalonamento"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Icaro Davies", email = "idavies@outlook.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.1",
]

[project.scripts]
am-tratamento-dados-escalonamento = "am_tratamento_dados_escalonamento:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
